name = "Comet Croft"
author = "AccursedGalaxy"
version = "0.1.0"
description = "A cozy Vanilla++ homestead pack: real seasons on the ground, comets and meteor falls in the sky."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5979744c92a76fcb53beab34139fd40156aa4cda2d1c72a9e1ed6c0cb5a56aff"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
