name = "Comet Croft"
author = "AccursedGalaxy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce499dfbad1da7a5ecb9636d5ddc607e04e9f2c6b12dafc3b499f1c172853ec"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1,26.1.1"]
